---
- name: Install php-fpm
  yum: name={{ item }}
  with_items:
    - php56-fpm

- name: Set php-fpm service to start on boot
  service: name=php-fpm enabled=true

- name: Put php-fpm.conf
  template: src=php-fpm.conf.j2 dest=/etc/php-fpm.conf backup=true mode=0644
  notify: restart php-fpm

- name: Put www.conf
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=true mode=0644
  notify: restart php-fpm
