- name: install php
  yum: pkg={{ item }} state=installed
  with_items:
    - php56
    - php56-devel
    - php56-mysqlnd
    - php56-mbstring
    - php56-gd
    - php56-cli
    - php56-dbg
    - php-pear
    - php56-pecl-memcached

- name: chmod php-session
  file: path=/var/lib/php/5.6/session mode=777
