---
- name: Install nginx
  yum: name=nginx state=latest

- name: Set nginx service to start on boot
  service: name=nginx enabled=true

- name: Put nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=true mode=0644
  notify: restart nginx

- name: Put monitaro.conf
  template: src={{ app_name }}.conf.j2 dest=/etc/nginx/conf.d/{{ app_name }}.conf backup=true mode=0644
  notify: restart nginx

- name: add sub_groups to deployer
  user: name={{deploy_user}} groups=nginx append=yes

- name: add sub_groups to nginx
  user: name=nginx groups={{deploy_user}} append=yes
